### ISSUE TITLE
Incorrect SAS URL path in HTTP POST method

### ISSUE THREAD

**Issue by pczeremuga** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#12]
Mock_SAS v2 is configured incorrectly and doesn't support SAS URL in HTTP POST method according to SAS-CBSD specifications document (page 24, WINNF-16-S-0016-V2.0.0).  The correct SAS URL shell be:
“/{sas_version_number}/{sas_method_name}”

However, current Mock_SAS v2 is configured with following string:
“/{sas_version_number}/{sas_method_name}/”

The addition of "/" shell be removed from flaskServer.py code and any other relevant areas of Mock_SAS server.  This incorrect formatting of SAS URL is causing CBSD Registration_Request failures and Mock_SAS server responds with “HTTP/1.0 404 NOT FOUND”.  Issue was observed and reproduced using Nokia CBSD.

**Comment by idanrazisr** [comment]
This issue is fixed as part of the CBRS_Mock_SAS_Python_Master uploaded on August 2nd 2017.
Now the "flaskServer.py" file line 12 has @app.route('/cbsd/<typeOfCalling>',methods=['POST'])
Please note to edit the  "flaskServer.py" file in a python editor to modify this line according to your CBSD. for example '/v2.0/<typeOfCalling>',methods=['POST'])
If the CBSD/Domain Proxy will still send the HTTP Request with a '/' at the end, the Mock-SAS will return HTTP 404. You can edit  "flaskServer.py" file in a python editor to modify this line to include again '/' :  '/v2.0/<typeOfCalling>/',methods=['POST']).

**Comment by awaizkhan** [comment]
Its agreed to go with the workaround to change the flaskserver.py to update the URL. However final fix would be to all CBSD vendors to update the correct URL based on the WinnF Standard.

**Comment by awaizkhan** [comment]
Nokia to verify V3.

**Comment by cwilliams-ericsson** [comment]
Fixed.  Close.
