### ISSUE TITLE
<MOCK SAS V3.0 Demo> list of objects should have template based verification

### ISSUE THREAD

**Issue by saudawar** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#26]
List of objects should have template based verification, so that all the list objects can be verified with single template.

**Comment by pawan25062** [comment]
Same as measReport handling, there need to be changes required for spectrum inquiry parameter object--> inquired spectrum. As CBSD can send chunks of frequency ranges. And when we tried same SI with latest Mock SAS, it is getting failed.

INFO: 09/18/2017 01:22:20 PM spectrumInquiry request from CBRS  : {
    "spectrumInquiryRequest": [
        {
            "cbsdId": "S9GQ710US01B42B4304Mock-SAS401629000040", 
            "inquiredSpectrum": [
                {
                    "highFrequency": 3560000000, 
                    "lowFrequency": 3550000000
                }, 
                {
                    "highFrequency": 3570000000,                           SI  request with chucks of frequency ranges (means in list of arrays for inquiredSpectrum)
                    "lowFrequency": 3560000000
                }, 
                {
                    "highFrequency": 3580000000, 
                    "lowFrequency": 3575000000
                }
            ]
        }
    ]
}
INFO: 09/18/2017 01:22:20 PM the server shot down because :  ERROR - An Error occurred while comparing between actual and expected requestin the json : idan4specinq1.json
INFO: 09/18/2017 01:22:21 PM The final result of the test : test is – FAIL

**Comment by ericzh31ericsson** [comment]
Please verify again with the new branch submitted by Ericsson in Oct. 20th
