### ISSUE TITLE
Mock-SAS failing test for Domain Proxy if CBSD #2 sends Registration Request after CBSD #1 finished all its steps

### ISSUE THREAD

**Issue by idanrazisr** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#39]
Current implementation of Mock-SAS requires that if UUT is Domain Proxy controlling 2 CBSDs, and for each CBSD there are individual Request/Response messages, then the first Request message of CBSD #2 must arrive to Mock-SAS before CBSD #1 finished all its steps listed in the CSV file. If CBSD #1 will conclude all its steps listed in the CSV file and only then CBSD #2 will start its steps listed in the CSV file, then current implementation of Mock-SAS will fail the test.

**Comment by cwilliams-ericsson** [comment]
Was not able to reproduce this directly.  However, noticed that, after one CBSD has finished its last step (but the other has not), if that CBSD sends any new request message, the test harness responses with a nonsense message.

Added a change so that, if CBSDx finishes its last step while CBSDy has not, then any additional message from CBSDx will get a canned response, designed to keep it "sane" while CBSDy completes it last step.  It will not allow new REG or GRA (provides responseCode 200 and 400, respectively), but will give SUCCESS responseCode to HBT, RLQ, DRG.

Note: this does not impact test harness responses after both CBSD finish the test.

**Comment by cwilliams-ericsson** [comment]
Now addressed in Pull-Request #77 and #71. 

Please try to reproduce.  I am able to run CBSD1 through entire test, plus further messages after last test step, prior to CBSD2 starting first step of test (REG), with a PASS for the test case.

**Comment by cwilliams-ericsson** [comment]
Fixed the canned responses in Engine.py that are sent if CBSD1 has finished test before CBSD2.  Did not put the canned-response in an array.   Done in bug-fixes-2018-January branch.

For example:
    heartbeatResponse: { ... }

should have been:
    heartbeatResponse: [ { ...} ]

With this, Engine.py can now append the canned response for CBSD1 properly.  Formerly it generated an exception which failed the test.

Now should be able to handle case of CBSD1 finishing test first.

**Comment by idanrazisr** [comment]
Issue not seen with latest release. Closing issue.
