### ISSUE TITLE
<Branch for Oct. 20th #46> installation parameter not being verified properly when defined in main JSON file

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#47]
[WINNF.FT.C.REG.3_2017-10-26T07.04.46Z.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1417697/WINNF.FT.C.REG.3_2017-10-26T07.04.46Z.zip)
Hi,

While executing REG test with installation parameters in main JSON file, SAS test harness giving following error.
Expected:
  {
      "antennaGain": "${range:-127To128}", 
      "height": "${range:0To10000}", 
      "heightType": {
          "$or": [
              "AGL", 
              "AMSL"
          ]
      }, 
      "indoorDeployment": {
          "$or": [
              "true", 
              "false"
          ]
      }, 
      "latitude": "${range:-90.000000To90.000000}", 
      "longitude": "${range:-180.000000To180.000000}"
  }
Actual:
  {
      "antennaGain": 3, 
      "eirpCapability": 30, 
      "height": 10, 
      "heightType": "AGL", 
      "indoorDeployment": true, 
      "latitude": 30.00000000001, 
      "longitude": -97.00000000001
  })
2017-10-26T07:05:01.926Z - INFO - the server shot down because :  for the CBRS with the cbsdSerialNumber :401629000040 ERROR - An Error occurred while comparing between actual and expected requestin the json : REG_SingleStep_CatA_Success_cbsd1.json
2017-10-26T07:05:02.585Z - INFO - The final result of the test : WINNF.FT.C.REG.3 is - FAIL

**Comment by cwilliams-ericsson** [comment]
Hi,

We took a look at this one and have a fix.  There needs to be some extra logic in Assert.py in order to handle a nested parameters, where some of the nested parameters are Required (in required Json) and some of the parameters are optional (not in required Json, but in optional schema).

I think this should only impact REG test cases, since the other test cases don't need to handle this case.

I will update the branch with the fix.

**Comment by pawan25062** [comment]
fix provided and it is working fine..
