### ISSUE TITLE
channelType missing in SpectrumInquiry response

### ISSUE THREAD

**Issue by dgcell20** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#51]
the channelType is missing in SpectrumInquiry response
issue appears to be related to if GAA is used the low and high frequencies were not accepting 3550000000 and 3700000000

**Comment by cwilliams-ericsson** [comment]
Work around as follows:
In CBRSRequestHandler.py, change line of code indicated below in def processSpectrumInquiryResponse():

                    if(itemReq["lowFrequency"]>=consts.SPECTRUM_GAA_LOW and itemReq["highFrequency"] < =consts.SPECTRUM_GAA_HIGH):
                        responseChannel["channelType"]="GAA"

ie. change ">" to ">=" and "<" to "<=".

A better solution will:
- if channelType and/or ruleApplied appear in jsonExpected file, use that value,
- otherwise use channelType = 'GAA' and ruleApplied = 'FCC_PART_96'

**Comment by pawan25062** [comment]
hi,
channelType is missing in SpectrumInquiry response, using master branch.
Are these changes available in main master branch?

**Comment by cwilliams-ericsson** [comment]
Issues 51 & 52 still exist in main branch (channelType missing from Grant Response, channelType missing in Spectrum Inquiry response).  Those fixes will be incorporated into next drop.

In the mean time, continue to use the fix provided (see those issue descriptions on GitHub).

Regards,

Chris

**Comment by dgcell20** [comment]
Validated
