### ISSUE TITLE
Handling of "The array of string lists" parameter (e.g. measCapability)

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#57]
Hi,

We have used following syntax for verification of measCapability in REG request:
"measCapability": {"$or":[["RECEIVED_POWER_WITHOUT_GRANT"],["RECEIVED_POWER_WITH_GRANT"],["RECEIVED_POWER_WITHOUT_GRANT", "RECEIVED_POWER_WITH_GRANT"] ]},

Now if CBSD sends request with measCapability as ""RECEIVED_POWER_WITHOUT_GRANT", "RECEIVED_POWER_WITH_GRANT"" SAS successfully respond to it.

But if CBSD sends request with measCapability as ""RECEIVED_POWER_WITH_GRANT", "RECEIVED_POWER_WITHOUT_GRANT"" SAS gives following error
 for the CBRS with the cbsdSerialNumber :401629000040 ERROR - the actual value : [u'RECEIVED_POWER_WITHOUT_GRANT', u'RECEIVED_POWER_WITH_GRANT'] is not one of the valid options in the json file 

log file is also attached here for reference.
[WINNF.FT.C.REG.3_2017-11-09T09.26.24Z.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1457120/WINNF.FT.C.REG.3_2017-11-09T09.26.24Z.zip)

**Comment by ericzh31ericsson** [comment]
You should add ‘RECEIVED_POWER_WITH_GRANT", "RECEIVED_POWER_WITHOUT_GRANT’ to your expected josn file, if you really want to check if the "measCapability" appears in the request message. i.e. it will be:
"measCapability": {"$or":[["RECEIVED_POWER_WITHOUT_GRANT"],["RECEIVED_POWER_WITH_GRANT"],["RECEIVED_POWER_WITHOUT_GRANT", "RECEIVED_POWER_WITH_GRANT"], ["RECEIVED_POWER_WITH_GRANT","RECEIVED_POWER_WITHOUT_GRANT"] ]}

But if you doesn’t care if it appears or not, then just remove it from the expected json. Because it has different way to check. If it appears in expected json file then it has to be same as what incoming message, here you missed one possibility. But if it is not in expected json file, Mock-SAS will using json schema to check and add it for the compare.

Thanks

Eric

**Comment by dgcell20** [comment]
Hi Pawan,
Taking Chris' advice, I have updated the JSON file that I believe you are using.

[REG_SingleStep_CatA_Success_cbsd1.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1457997/REG_SingleStep_CatA_Success_cbsd1.zip)

**Comment by awaizkhan** [comment]
@pawan25062  can you please update the ticket with your observation?

**Comment by cwilliams-ericsson** [comment]
Work around provided
