### ISSUE TITLE
SAS test harness shot down server after test case failure

### ISSUE THREAD

**Issue by pawan25062** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#68]
Hi,

We tried executing test case "WINNF.FT.C.MES.4_measConf_in_HB".
But SAS test harness shot down server after test case failure.
2017-11-20T12:18:21.816Z - INFO - the server shot down because :  ERROR - no meas report received in the last 5 heart beats request
2017-11-20T12:18:22.690Z - INFO - The final result of the test : WINNF.FT.C.MES.4_measConf_in_HB is - FAIL

![image](https://user-images.githubusercontent.com/31058265/33019267-96f5a2cc-ce1f-11e7-9645-f424beccb088.png)
[WINNF.FT.C.MES.4_measConf_in_HB_2017-11-20T12.06.10Z.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1487663/WINNF.FT.C.MES.4_measConf_in_HB_2017-11-20T12.06.10Z.zip)

log file is also attached here for your reference.

**Comment by cwilliams-ericsson** [comment]
This works fine for me, provided you are using pull-request #59 branch, and the commit as of Friday, Nov 17 (commit: a321b0b9ef87f4854168313637de6023e73f6386).

Can you please check if you have the latest updates, and confirm whether this problem still exists for you?  Thanks.

**Comment by pawan25062** [comment]
hi,

Again tried the same test case with current master branch and same issue observed:
2017-12-06T12:46:39.358Z - INFO - heartbeat request from CBRS  : {
    "heartbeatRequest": [
        {
            "cbsdId": "S9GQ710US01Mock-SAS401629000040", 
            "grantId": "528509500", 
            "operationState": "AUTHORIZED"
        }
    ]
}
2017-12-06T12:46:39.358Z - INFO - The time interval between two heartbeat request messages is 120.011
2017-12-06T12:46:39.358Z - INFO - the server shot down because :  ERROR - the duration between the heartbeats are more then expected from json file
2017-12-06T12:46:40.232Z - INFO - The final result of the test : WINNF.FT.C.MES.4_measConf_in_HB is - FAIL

log file is attached here for refer
[WINNF.FT.C.MES.4_measConf_in_HB_2017-12-06T12.36.11Z.zip](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1535195/WINNF.FT.C.MES.4_measConf_in_HB_2017-12-06T12.36.11Z.zip)
ence.

**Comment by cwilliams-ericsson** [comment]
Hi Pawan,

It is not the same issue observed.  In fact, you are seeing an entirely different problem.  The original problem was failure due to "no meas report received in the last 5 heartbeats".  That has been fixed for this test case.

What your latest log states now is "ERROR - the duration between the heartbeats are more than expected from json file".

If you look at the log, you will see the time between heartbeat requests as:

119.98 sec
119.995 sec
119.996 sec
119.995 sec
120.011 sec

You are running this test with heartbeatInterval = 120 sec, so the last hearbeat arrives too late.  That is why your CBSD is now failing the test.  This is not the same as the original issue.

I would suggest that your CBSD implementation should change to ensure your heartbeats are guaranteed to arrive within the heartbeatInterval.  The CBSD log indicates that your implementation is running very close to the edge and potentially will fail any test case where multiple heartbeats occur.

**Comment by cwilliams-ericsson** [comment]
Fixed with implementation of "grace period" on heartbeat interval
