### ISSUE TITLE
WINNF.FT.C.MES.1 test case measReportConfig seen as a string

### ISSUE THREAD

**Issue by dgcell20** [Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device#93]
As per specifications, measReportConfig should be an ‘array of strings’. The value being sent in the registrationResponse message is a single string, not contained in an array. Even though the MES_registration_MeasConf_Cbsd1.json shows it as an array.

The log file has:
2018-01-09T10:10:33.930Z - INFO - engine sent successfully, the response to CBRS  : {
    "registrationResponse": [
        {
            "cbsdId": "1234567890123456789Mock-SASEB1734120340", 
            "measReportConfig": "RECEIVED_POWER_WITHOUT_GRANT", 
            "response": {
                "responseCode": 0
            }
        }
    ]

MES_registration_MeasConf_Cbsd1.json has:
  "response":{
                 "registrationResponse" :[
                      {
    				    "measReportConfig" : ["RECEIVED_POWER_WITHOUT_GRANT"],                         
                        "response": {
                               "responseCode": 0
                               }
                       }
                                     
                   ]
	          }

**Comment by cwilliams-ericsson** [comment]
Hi Doug,

Can you provide any more information?  This was fixed in Dec 22 commit.  I downloaded the latest Master branch this morning and tried to reproduce with test case WINNF.FT.C.MES.1 and my logs show the measReportConfig is an array (see below).  I can't figure out how the test harness could remove the array, since the parameter is read directly from the json file, and should be unaltered.  Can you re-verify your setup?

2018-01-10T13:22:08.331Z - INFO - Response message contains measReportConfig
2018-01-10T13:22:08.331Z - INFO - engine sent successfully, the response to CBRS  : {
    "registrationResponse": [
        {
            "cbsdId": "EricssonFCCID1A3B5CMock-SASD823956047", 
            "measReportConfig": [
                "RECEIVED_POWER_WITHOUT_GRANT"
            ], 
            "response": {
                "responseCode": 0
            }
        }
    ]
}

**Comment by dgcell20** [comment]
Using the newer commit, measReportConfig is an ‘array of strings’. 
Test case is now failing at a later point.
Spectrum inquiry request is sent including the measReport information.
The spectrumInquiryResponse is not including the availableChannel information, which is expected. We then send another request, and obtain same response.
See attached log file
[WINNF.FT.C.MES.1_2018-01-24T08.00.24Z.log](https://github.com/Wireless-Innovation-Forum/Citizens-Broadband-Radio-Service-Device/files/1662159/WINNF.FT.C.MES.1_2018-01-24T08.00.24Z.log)

**Comment by cwilliams-ericsson** [comment]
Fixed in working branch.

**Comment by dgcell20** [comment]
Verified
